#git 中测试文件
spring:
  profiles:
    active:
    - dev 
---  
server:
  port: 8201
spring: 
  profiles: dev
  application:
    name: microclient-config-client
eureka: 
  client:
    service-url:  #进行eureka注册中心的集群注册
      defaultZone: http://admin:admin@eureka-config-7301:7301/eureka
---
server:
  port: 8201
spring:
  proflies: beta    
  application:
    name: microclient-config-client
config:
  info: aaaaaaaaaaa    
eureka: 
  client:
    service-url:  #进行eureka注册中心的集群注册
      defaultZone: http://127.0.0.1:7001/eureka
