spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
#security:
#  sessions: stateless #session无状态协议
#  basic:
#    enabled: true # 启用SpringSecurity的安全配置项
#  user:
#    name: springcloud  # 认证用户名
#    password: zhang # 认证密码
#    role:        # 授权角色
#    - USER
#security: #一下url不进行安全认证拦截 主要用于turbine
#  ignored:
#  - hystrix.stream
#  - turbine.stream

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:admin@eureka-config-7301:7301/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: microcloud-dev-config-client-provider-8001  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址

info:  #设置eureka注册中心得info信息
  app.name: mldn-microcloud
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: org.microcloud.entity          # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/springcloud1          # 数据库连接地址
    username: root                                  # 数据库用户名
    #password: '{cipher}AQCV3+Rp25WjZOqitt8MYp+48KscaeALJNplLIkLiCXyYWqIsJKqV36eCW0MhMPomzY84yHmJfDD9azGw9vUqudo5Fg9TWXH5WOTJO/6Q3psI+byJRktxqsSLoECRxamuqla+SK6Z/RDRvaDhjYORymhaJCdVan75G+upu9dmqULSWypUVHYQbvQOYv2aRALPPvmhCI5oyt382oVItcVroDkjQcrd03irlnwIHqBl21Zk/TzdTRsM27Fx3nP5SNAYwQJ9x0Aqizmy6xzSME0dFgtzFN2tB9uOlbmAfTEgUjCacuyD3GwT36f2Jk/eZcaDJp4s/JT7XpBWisNgv6D2evYyyBsQNiA7MMc2Tq2JxJNZ2qRPgwKXMGP182FfqmJKiw='                            # 数据库连接密码
    password: 123456
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  application:
    name: microcloud-config-client-provider
  profiles: dev
 
---
server:
  port: 8001
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:admin@eureka-config-7301:7301/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: microcloud-beta-config-client-provider-8001  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址

info:  #设置eureka注册中心得info信息
  app.name: mldn-microcloud
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: org.microcloud.entity          # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/springcloud1          # 数据库连接地址
    username: root                                  # 数据库用户名
    #password: '{cipher}AQCV3+Rp25WjZOqitt8MYp+48KscaeALJNplLIkLiCXyYWqIsJKqV36eCW0MhMPomzY84yHmJfDD9azGw9vUqudo5Fg9TWXH5WOTJO/6Q3psI+byJRktxqsSLoECRxamuqla+SK6Z/RDRvaDhjYORymhaJCdVan75G+upu9dmqULSWypUVHYQbvQOYv2aRALPPvmhCI5oyt382oVItcVroDkjQcrd03irlnwIHqBl21Zk/TzdTRsM27Fx3nP5SNAYwQJ9x0Aqizmy6xzSME0dFgtzFN2tB9uOlbmAfTEgUjCacuyD3GwT36f2Jk/eZcaDJp4s/JT7XpBWisNgv6D2evYyyBsQNiA7MMc2Tq2JxJNZ2qRPgwKXMGP182FfqmJKiw='                            # 数据库连接密码
    password: 123456
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  application:
    name: microcloud-config-client-provider
  profiles: beta
  
